version: '3'
services:
  gh_runner:
    image: paslavsky/gh_runner:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_TOKEN=${GH_TOKEN}
    volumes:
    - ./_work:/usr/actions-runner/_work/