---
micronaut:
    application:
        name: micronaut-jpa

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    packages-to-scan:
      - 'micronaut.jpa'
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update


---
datasources.default: {}