name: GitHub Pages

on:
  push:
    branches:
      - 'master'

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: cd web-view && npm install
      - name: Deploy
        if: success()
        run: cd web-view && npm run deploy
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}