name: Measure

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Grant execute permission for run.sh
      run: chmod +x run.sh
    - name: Collect metrics
      run: ./run.sh
